after-login-command = []
after-startup-command = []
start-at-login = true
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
accordion-padding = 0
default-root-container-layout = 'accordion'
default-root-container-orientation = 'auto'
key-mapping.preset = 'qwerty'
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = ['move-mouse window-lazy-center']

[gaps]
inner.horizontal = 0
inner.vertical =   0
outer.left =       0
outer.bottom =     0
outer.top =        0
outer.right =      0

[workspace-to-monitor-force-assignment]
5 = 'secondary'

[mode.main.binding]
cmd-f1 = 'workspace 1'
cmd-f2 = 'workspace 2'
cmd-f3 = 'workspace 3'
cmd-f4 = 'workspace 4'
cmd-f5 = 'workspace 5'
cmd-f6 = 'workspace 6'
cmd-f7 = 'workspace 7'
cmd-f8 = 'workspace 8'
cmd-f9 = 'workspace 9'
cmd-f10 = 'workspace 10'

cmd-ctrl-f1 = 'move-node-to-workspace 1'
cmd-ctrl-f2 = 'move-node-to-workspace 2'
cmd-ctrl-f3 = 'move-node-to-workspace 3'
cmd-ctrl-f4 = 'move-node-to-workspace 4'
cmd-ctrl-f5 = 'move-node-to-workspace 5'
cmd-ctrl-f6 = 'move-node-to-workspace 6'
cmd-ctrl-f7 = 'move-node-to-workspace 7'
cmd-ctrl-f8 = 'move-node-to-workspace 8'
cmd-ctrl-f9 = 'move-node-to-workspace 9'
cmd-ctrl-f10 = 'move-node-to-workspace 10'

cmd-f11 = 'mode move'
cmd-f12 = 'mode focus'
cmd-f13 = 'focus left --boundaries-action wrap-around-the-workspace'
cmd-f16 = 'focus right --boundaries-action wrap-around-the-workspace'
cmd-ctrl-f13 = 'focus up --boundaries-action wrap-around-the-workspace'
cmd-ctrl-f16 = 'focus down --boundaries-action wrap-around-the-workspace'
cmd-f17 = 'mode service'

[mode.focus.binding]
cmd-f11 = 'mode move'
cmd-f12 = 'mode main'
cmd-f13 = 'focus left --boundaries-action wrap-around-the-workspace'
cmd-f16 = 'focus right --boundaries-action wrap-around-the-workspace'
cmd-ctrl-f13 = 'focus up --boundaries-action wrap-around-the-workspace'
cmd-ctrl-f16 = 'focus down --boundaries-action wrap-around-the-workspace'
cmd-f17 = 'mode service'
esc = 'mode main'

left = 'focus left'
down = 'focus down'
up = 'focus up'
right = 'focus right'

shift-up = 'resize width -50'
shift-right = 'resize width +50'
shift-left= 'resize height -50'
shift-down = 'resize height +50'

[mode.move.binding]
cmd-f11 = 'mode main'
cmd-f12 = 'mode focus'
cmd-f13 = 'focus left --boundaries-action wrap-around-the-workspace'
cmd-f16 = 'focus right --boundaries-action wrap-around-the-workspace'
cmd-ctrl-f13 = 'focus up --boundaries-action wrap-around-the-workspace'
cmd-ctrl-f16 = 'focus down --boundaries-action wrap-around-the-workspace'
cmd-f17 = 'mode service'
esc = 'mode main'

left = 'move left'
down = 'move down'
up = 'move up'
right = 'move right'

shift-up = 'resize width -50'
shift-right = 'resize width +50'
shift-left= 'resize height -50'
shift-down = 'resize height +50'

[mode.service.binding]
cmd-f11 = 'mode move'
cmd-f12 = 'mode focus'
cmd-f13 = 'focus left --boundaries-action wrap-around-the-workspace'
cmd-f16 = 'focus right --boundaries-action wrap-around-the-workspace'
cmd-ctrl-f13 = 'focus up --boundaries-action wrap-around-the-workspace'
cmd-ctrl-f16 = 'focus down --boundaries-action wrap-around-the-workspace'
cmd-f17 = 'mode service'
esc = ['reload-config', 'mode main']
# (a)lternate layout
cmd-f1 = ['layout accordion tiles', 'mode main']
# (s)end to next monitor
cmd-f2 = ['move-node-to-monitor --wrap-around next', 'focus-monitor --wrap-around next', 'mode main']
# (d)isable
cmd-f3 = ['layout floating tiling', 'mode main']
# (f)ullscreen
cmd-f4 = ['fullscreen', 'mode main']
# (r)eset
cmd-f9 = ['flatten-workspace-tree', 'mode main']
backspace = ['close-all-windows-but-current', 'mode main']


left = 'exec-and-forget skhd -k "home"'
down = 'exec-and-forget skhd -k "pagedown"'
up = 'exec-and-forget skhd -k "pageup"'
right = 'exec-and-forget skhd -k "end"'

1 = 'exec-and-forget skhd -k "f1"'
2 = 'exec-and-forget skhd -k "f2"'
3 = 'exec-and-forget skhd -k "f3"'
4 = 'exec-and-forget skhd -k "f4"'
5 = 'exec-and-forget skhd -k "f5"'
6 = 'exec-and-forget skhd -k "f6"'
7 = 'exec-and-forget skhd -k "f7"'
8 = 'exec-and-forget skhd -k "f8"'
9 = 'exec-and-forget skhd -k "f9"'
0 = 'exec-and-forget skhd -k "f10"'

shift-1 = 'exec-and-forget skhd -k "shift - f1"'
shift-2 = 'exec-and-forget skhd -k "shift - f2"'
shift-3 = 'exec-and-forget skhd -k "shift - f3"'
shift-4 = 'exec-and-forget skhd -k "shift - f4"'
shift-5 = 'exec-and-forget skhd -k "shift - f5"'
shift-6 = 'exec-and-forget skhd -k "shift - f6"'
shift-7 = 'exec-and-forget skhd -k "shift - f7"'
shift-8 = 'exec-and-forget skhd -k "shift - f8"'
shift-9 = 'exec-and-forget skhd -k "shift - f9"'
shift-0 = 'exec-and-forget skhd -k "shift - f10"'
